### PR TITLE
12.0 fix fieldservice recurring

### PR DESCRIPTION
**Pull request by mourad-ehm**
@kittiu @hpar

### CODE REVIEW

**Comment by kittiu** [comment]
@mourad-ehm why not merge to the OCA repo? Would it be faster to get merged?

My branch is mainly aim for test script ;)

**Comment by mourad-ehm** [comment]
Because my PR concern fieldservice_recurring which is not still migrated.

**Comment by kittiu** [comment]
I see your point now. But I am new here too, @brian10048, would you help?

**Comment by brian10048** [comment]
@kittiu I reviewed and approved the PR to migrate fieldservice_recurring.  We should see it merged soon into the OCA

@mourad-ehm I would suggest submitting your changes to the OCA branch once that PR is merged

**Comment by kittiu** [comment]
@brian10048 noted and thank you.

**Comment by kittiu** [comment]
@mourad-ehm sorry, I just check this. Should this one get closed? You moved to OCA?

**Pull request closed without merging**
